language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required

before_install:
  - export PUBLISH_BINARY="false"
  - export BUILD_SWITCHES=""
  - export BUILD_TYPE="Debug";

  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      export PUBLISH_BINARY="true";
      export PUBLISH_DIR="pull-requests/$TRAVIS_PULL_REQUEST";
      export VERSION_TAG="${TRAVIS_PULL_REQUEST}pullrequest";
    fi
  - if [[ "$NIGHTLY_VERSION" != "" ]]; then
      export PUBLISH_BINARY="true";
      export PUBLISH_DIR="nightlies";
      export VERSION_TAG="$NIGHTLY_VERSION";
    fi
  - if [[ "$TRAVIS_TAG" != "" ]]; then
      export BUILD_TYPE="Release";
      export PUBLISH_BINARY="true";
      export PUBLISH_DIR="releases";
      export VERSION_TAG="";
    fi

  - export BUILD_SWITCHES="-DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVERSION_TAG=$VERSION_TAG"
  - if [ "$PUBLISH_BINARY" == "true" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export BUILD_SWITCHES="$BUILD_SWITCHES -DCMAKE_INSTALL_PREFIX=/usr -DEXTRA_DATA_DIR=/usr/share/ja2 -DLOCAL_BOOST_LIB=ON";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export BUILD_SWITCHES="$BUILD_SWITCHES -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-macos.cmake -DCPACK_GENERATOR=Bundle";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export BUILD_SWITCHES="$BUILD_SWITCHES -DCPACK_GENERATOR=DEB";
    fi

  - echo "$PUBLISH_BINARY"
  - echo "$PUBLISH_DIR"
  - echo "$BUILD_SWITCHES"

  - curl -sSf https://static.rust-lang.org/rustup.sh | sh
  - cargo -V
  - rustc -V

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      fakeroot -v;
    fi

script:
  - mkdir ci-build && cd ci-build
  - cmake $BUILD_SWITCHES ..;
  - make
  - if [ "$PUBLISH_BINARY" == "true" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo make install;
    fi
  - make rust-unit-tests
  - ./ja2 -unittests
  - ./ja2-launcher -help
  - if [ "$PUBLISH_BINARY" == "true" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo make uninstall;
    fi
  - if [ "$PUBLISH_BINARY" == "true" ]; then
      make package;
    fi
  - if [ "$PUBLISH_BINARY" == "true" ] && [ "$SFTP_PASSWORD" != "" ]; then
      curl --ftp-create-dirs -T $(echo ja2-stracciatella_*) --ftp-ssl -u $SFTP_USER:$SFTP_PASSWORD ftp://www61.your-server.de/$PUBLISH_DIR/;
    fi

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - libsdl2-dev
    - libboost-all-dev
    - fluid
    - libfltk1.3-dev
    - fakeroot
  coverity_scan:
    project:
      name: "ja2-stracciatella/ja2-stracciatella"
      description: "Build submitted via Travis CI"
    notification_email: github@stefanlau.com
    build_command_prepend: "mkdir coverage-build && cd coverage-build && cmake .."
    build_command:   "make"
    branch_pattern: coverity-via-travis

env:
  global:
    - secure: "o8hCOxRt+3jpgLHEQgvHSSY5eIAq+yrAprSaOYZ5YZcj0Xztcu/oCbxZ3l9t6arY91yqHDjzyuSJMrLrGigjYIR/Bp26Du9o1MA/j+FmP2I8Uwn1lyBI1hyZtX5Viuktpkcpdfiv52ISbFPnHmJ0JjgsbLqqnGw8Ps2zoYrFlI284d9FxPZJfjt8pzZLBAB77zE0rMKGO1ITRV6FJbG2Wjh5A165gx4yM3UszyA01jVR/ifFItdGfSzJB3UXroFjzxL7TNP9WgQjBEcmup6y7E90PztFGFBVwvBnEHMWwb4Wr8NuFmhMRXbOb5ilw7rwXeeeKBQ2pAShY0A4N5k6Ah6oJcR7+I59eSscnjq0gJVmLkRPUij6RQtL+WgSFQ4EssyTONOelQhEPV4NU5jUleTHES5mFVy8Ndz4gULb9aX/uXRp2aV0fpqDcNnpdZJO1M3upCNxC9X9U3jmQC6MgDElaoyBb4IC1+XDOBq2XbTpLn58IbZUr975S/EIMENXhUl58FohhwuhQMyYqz/C+/A8lOvDQ0v3eOVIqdOgxNuxlAUs3DJAai8xDDVUfYUizcwKNFGo96aD2+eJQ9GeQ1P0uHIzP+BmQidFaZZIVmbEyjVRN8xKIA6TQKQLL0eStm/FHkjMMu3MrfvuDJcJmxcoQQWCFWHKSLGaHLI6xHc="
    - secure: "hGKZH6OhE4695iUBAOIUI1j6ZySnsBr/vMMLP3yEgOgEcpV4uHZd7ksEDMQ3O7sbc3YGA0a5dBZZmBktJF7FWYazcy7X7G2UTDNuigYdEcsD46XqJ+f9c91QofOsyvg2OFFU98ORJ7Q2l6a7aemdM/UAwEiM1MV65TMkPZURwEGD6iXI7JtbZI0llfHeXhccksqrO/GUH8VyfYn0LA71dagxzcGHThndCTqizqxtkiI0bUquXErt4w09faie2gB0pwRBSZvlYMHaqcsoC8WcGy5upUPxIX5hfpGrHMwpcHH2S3k6OWNYhILFYqfR/2p4zlnzwXC27YETMO9XOGVjZegePkRRR1iurW5KtVVy8a7Ap/CmS3VC99yvGIRMDJIgSLQku8GC4GRSNjPUXvhP0Sf6NEN5xCyy/zlD3KGJelBXjoGzlhFRUIqamo7ahrnIjtO0op2Z7EOcfNP5146EJnMTA1Nk07x5y9TSdveLvbFziI3ak6VSF+prffwoET5AOYddUNlWdjdtEEK/m/kKYyUa1dlgFVzBwwcpfSD3aJbKtwLAeQf3gUDrHX/WQD1srT2vnt8Zk4c+mTPn3l7Qt/ygot2NFKTnxW7sjD/rdVYDHh99M3I/lCI16TFt7GnJ7/DPqf8vqOld6ubfu/+ExdkFvVFfoYTDpNgXyDEyCWM="
    - secure: "aCkkzCZe/Vm5eaL/Rg+CPeBVS5/WeAFmgIY/RueI61tj2WnjrgoE58hftOcg7oIptdz2heQTEB16aUpt6W+wqGKRSGKeo8G/y/Q08WNLcVgomDvfT6snQKm/LVcxc6a9sN7HZgWGdfkHVUP3tA/wTO2w/nKKIrMu3PmeSMkCJlM6CV8TQO/daOfJMUWkIImrzBO5E2lK11a/G4w/RxS0BKhnR6F/VEfvAkh/CDV/BK8Fpeiowk3bvIMA8Bc/Ect03A5mf2y17E9uFI2KEk77cll/bAp/GlwiE0YEjBfY0q6agHREHL605CGAQUkYGrZCrP6gGX/X/b7hjcCaOTV5DdoDCXiceINMxb2x/cKPyMTP5vAHpy+3PnZM2P18UzYwPmo8+3BCE5fhNBJ3xeFK9HkzjCbfW5REMcQ5bY1a+Yc5Alf4dNe+Q5b0hLBPtgm9cgxIXft6fIRBTS9xV9bHWgiEySgCpfPNAE9jqyb+gpoXtPLowVbuc2WsGW1XpUXvbGyCsyFQX0mAoH8SbfInJd6oAwS3Dg8/Ver6X1NjBzFvqI6xHxR+Io8TQ3P5PF30k17X8FitgDOZ/9VvnA9wi8/pxc8zV+2qQF//3UX6KKcxDKAFlIugLOknssof1p4pWcRPI8nhXB5m0ce//bX5To1FwJrEs5ryNfQTQBnr1Ow="
