[workspace]
members = [
    "stracciatella",
    "stracciatella_bin",
    "stracciatella_c_api",
]

[profile.dev]
rpath = true
panic = "abort"

[profile.release]
rpath = true
debug = true
panic = "abort"

